// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/world/cardinal/cardinal.go
//
// Generated by this command:
//
//	mockgen -source cmd/world/cardinal/cardinal.go -destination cmd/world/cardinal/mock/cardinal.go
//

// Package mock_cardinal is a generated GoMock package.
package mock_cardinal

import (
	reflect "reflect"

	cobra "github.com/spf13/cobra"
	gomock "go.uber.org/mock/gomock"
)

// MockCardinal is a mock of Cardinal interface.
type MockCardinal struct {
	ctrl     *gomock.Controller
	recorder *MockCardinalMockRecorder
}

// MockCardinalMockRecorder is the mock recorder for MockCardinal.
type MockCardinalMockRecorder struct {
	mock *MockCardinal
}

// NewMockCardinal creates a new mock instance.
func NewMockCardinal(ctrl *gomock.Controller) *MockCardinal {
	mock := &MockCardinal{ctrl: ctrl}
	mock.recorder = &MockCardinalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardinal) EXPECT() *MockCardinalMockRecorder {
	return m.recorder
}

// GetBaseCmd mocks base method.
func (m *MockCardinal) GetBaseCmd() *cobra.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseCmd")
	ret0, _ := ret[0].(*cobra.Command)
	return ret0
}

// GetBaseCmd indicates an expected call of GetBaseCmd.
func (mr *MockCardinalMockRecorder) GetBaseCmd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseCmd", reflect.TypeOf((*MockCardinal)(nil).GetBaseCmd))
}
