// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/world/root/root.go
//
// Generated by this command:
//
//	mockgen -source cmd/world/root/root.go -destination cmd/world/root/mock/root.go
//

// Package mock_root is a generated GoMock package.
package mock_root

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoot is a mock of Root interface.
type MockRoot struct {
	ctrl     *gomock.Controller
	recorder *MockRootMockRecorder
}

// MockRootMockRecorder is the mock recorder for MockRoot.
type MockRootMockRecorder struct {
	mock *MockRoot
}

// NewMockRoot creates a new mock instance.
func NewMockRoot(ctrl *gomock.Controller) *MockRoot {
	mock := &MockRoot{ctrl: ctrl}
	mock.recorder = &MockRootMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoot) EXPECT() *MockRootMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRoot) Execute() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Execute")
}

// Execute indicates an expected call of Execute.
func (mr *MockRootMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRoot)(nil).Execute))
}
