name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:
    inputs:
      create_release:
        description: 'Check if workflows called from Github Release event.'
        default: false
        required: false
        type: boolean

jobs:
  go-build:
    name: Run Go Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: "go.sum"
      - name: Build ${{ matrix.goos }}/${{ matrix.goarch }}
        id: build
        run: |
          output_name=world_${{ matrix.goos }}_${{ matrix.goarch }}
          [ ${{ matrix.goos }} = "windows" ] && output_name+=".exe"

          ## Get version from tag name
          $bin_version=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          ## Handle if event coming from PR, not release/tag
          [ "$bin_version" == "merge" ] && bin_version=${{ github.event.pull_request.head.sha }}

          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags "-X main.AppVersion=$bin_version -X main.SentryDsn=${{ secrets.SENTRY_DSN }} -X main.PosthogApiKey=${{ secrets.POSTHOG_API_KEY }}" -o $output_name ./cmd/world
          echo "output_name=$output_name" >> $GITHUB_OUTPUT
      - name: Compress Build Binary
        uses: a7ul/tar-action@v1.1.3
        id: compress
        with:
          command: c
          files: |
            ./${{ steps.build.outputs.output_name }}
          outPath: ${{ steps.build.outputs.output_name }}.tar.gz
      - name: Upload binary to Github artifact
        if: ${{ inputs.create_release }}
        uses: actions/upload-artifact@v3
        with:
          name: world-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./world*.tar.gz
