name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:
    inputs:
      create_release:
        description: 'Check if workflows called from Github Release event.'
        default: false
        required: false
        type: boolean

jobs:
  build-go:
    name: Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: "go.sum"
      - name: Build
        run: make build
