name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:
    inputs:
      create_release:
        description: 'Check if workflows called from Github Release event.'
        default: false
        required: false
        type: boolean
env:
  GO_VERSION: 1.21.1

jobs:
  build-go:
    name: Go
    runs-on: namespace-profile-linux-4vcpu-8gb-cached
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          ## skip cache, use Namespace volume cache
          cache: false
      - name: Build
        run: make build
