name: Release

on:
  release:
    types: [created]

jobs:
  go-test:
    name: Test
    uses: ./.github/workflows/test.yml

  go-build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Release world-cli binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
    steps:
      - name: Download world-cli build binary
        uses: actions/download-artifact@v3
        with:
          name: world-cli
      - name: Publish world-cli binary to corresponding Github Release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'world-cli'
