name: Release

on:
  release:
    types: [created]

jobs:
  go-test:
    name: Test
    uses: ./.github/workflows/test.yml@${{ github.sha }}

  go-build:
    name: Build
    uses: ./.github/workflows/build.yml@${{ github.sha }}

  go-build:
    name: Run Go Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
    steps:
      - name: Download coverage output file
        uses: actions/download-artifact@v3
        with:
          name: world-cli
      - name: Publish binary to Github Release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'world-cli'
