name: Release

on:
  release:
    types: [created]

env:
  GORELEASER_VERSION: '~> v2'
  GO_VERSION: 1.24.0

permissions:
  contents: write

jobs:
  go-test:
    name: Test
    runs-on: namespace-profile-linux-4vcpu-8gb-cached
    uses: ./.github/workflows/test.yml

  goreleaser:
    name: Release World CLI binary
    runs-on: namespace-profile-linux-4vcpu-8gb-cached
    needs: go-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run World CLI goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: ${{ env.GORELEASER_VERSION }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
